// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owhaedefhgwbbrzljdnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93aGFlZGVmaGd3YmJyemxqZG5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0ODIwNDksImV4cCI6MjA3MzA1ODA0OX0.CQHlCZu-B2Fyp0_6JHGeDgla9bDb5jDWN6hxdVLJoFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});